<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" ignored="0" total="4" passed="2">
  <reporter-output>
    <line>
      <![CDATA[About to begin test Test1]]>
    </line>
    <line>
      <![CDATA[About to begin test Test1]]>
    </line>
    <line>
      <![CDATA[About to begin test Test1]]>
    </line>
    <line>
      <![CDATA[test success Test1]]>
    </line>
    <line>
      <![CDATA[About to begin test Test2]]>
    </line>
    <line>
      <![CDATA[test success Test2]]>
    </line>
  </reporter-output>
  <suite name="Multibrowser" duration-ms="47" started-at="2019-04-23T12:24:43Z" finished-at="2019-04-23T12:24:44Z">
    <groups>
    </groups>
    <test name="testwithfirefox" duration-ms="47" started-at="2019-04-23T12:24:43Z" finished-at="2019-04-23T12:24:44Z">
      <class name="testNgTutorial.RetryClassTest">
        <test-method status="SKIP" signature="Test1()[pri:0, instance:testNgTutorial.RetryClassTest@7dc7cbad]" name="Test1" duration-ms="12" started-at="2019-04-23T17:54:43Z" finished-at="2019-04-23T17:54:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at org.testng.Assert.assertEquals(Assert.java:314)
	at testNgTutorial.RetryClassTest.Test1(RetryClassTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[About to begin test Test1]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method status="SKIP" signature="Test1()[pri:0, instance:testNgTutorial.RetryClassTest@7dc7cbad]" name="Test1" duration-ms="1" started-at="2019-04-23T17:54:44Z" finished-at="2019-04-23T17:54:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at org.testng.Assert.assertEquals(Assert.java:314)
	at testNgTutorial.RetryClassTest.Test1(RetryClassTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[About to begin test Test1]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method status="PASS" signature="Test1()[pri:0, instance:testNgTutorial.RetryClassTest@7dc7cbad]" name="Test1" duration-ms="2" started-at="2019-04-23T17:54:44Z" finished-at="2019-04-23T17:54:44Z">
          <reporter-output>
            <line>
              <![CDATA[About to begin test Test1]]>
            </line>
            <line>
              <![CDATA[test success Test1]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method status="PASS" signature="Test2()[pri:0, instance:testNgTutorial.RetryClassTest@7dc7cbad]" name="Test2" duration-ms="1" started-at="2019-04-23T17:54:44Z" finished-at="2019-04-23T17:54:44Z">
          <reporter-output>
            <line>
              <![CDATA[About to begin test Test2]]>
            </line>
            <line>
              <![CDATA[test success Test2]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test2 -->
      </class> <!-- testNgTutorial.RetryClassTest -->
    </test> <!-- testwithfirefox -->
  </suite> <!-- Multibrowser -->
</testng-results>
